global:
  datacenter: demo

server:
  replicas: 1
  bootstrapExpect: 1

client:
  enabled: true

ui:
  enabled: true
  service:
    type: 'NodePort'

connectInject:
  enabled: true
  imageEnvoy: envoyproxy/envoy
